ALTER TABLE t_p75921280_team_flux_website.members
  ADD COLUMN faceit_lvl INT DEFAULT NULL,
  ADD COLUMN faceit_elo INT DEFAULT NULL,
  ADD COLUMN kd_ratio NUMERIC(4,2) DEFAULT NULL,
  ADD COLUMN matches_played INT DEFAULT 0,
  ADD COLUMN matches_won INT DEFAULT 0,
  ADD COLUMN favorite_weapon VARCHAR(60) DEFAULT NULL,
  ADD COLUMN motto VARCHAR(200) DEFAULT NULL